In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.layers import Dense, Activation, CuDNNLSTM, LSTM, Dropout
from keras.models import Sequential



In [0]:
file = open('alice.txt','r')
data = file.read()

In [0]:
data

'CHAPTER I. Down the Rabbit-Hole\n\nAlice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, ‘and what is the use of a book,’ thought Alice ‘without pictures or\nconversations?’\n\nSo she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and stupid), whether the pleasure\nof making a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a White Rabbit with pink eyes ran\nclose by her.\n\nThere was nothing so VERY remarkable in that; nor did Alice think it so\nVERY much out of the way to hear the Rabbit say to itself, ‘Oh dear!\nOh dear! I shall be late!’ (when she thought it over afterwards, it\noccurred to her that she ought to have wondered at this, but at the time\nit all seemed quite natural); but when the Rabbit actually TOOK A WATCH

In [0]:
len(data)

163105

In [0]:
from nltk.tokenize import word_tokenize

In [0]:
import nltk

In [0]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [0]:
data1= word_tokenize(data)

In [0]:
data1

['CHAPTER',
 'I',
 '.',
 'Down',
 'the',
 'Rabbit-Hole',
 'Alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'bank',
 ',',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'do',
 ':',
 'once',
 'or',
 'twice',
 'she',
 'had',
 'peeped',
 'into',
 'the',
 'book',
 'her',
 'sister',
 'was',
 'reading',
 ',',
 'but',
 'it',
 'had',
 'no',
 'pictures',
 'or',
 'conversations',
 'in',
 'it',
 ',',
 '‘',
 'and',
 'what',
 'is',
 'the',
 'use',
 'of',
 'a',
 'book',
 ',',
 '’',
 'thought',
 'Alice',
 '‘',
 'without',
 'pictures',
 'or',
 'conversations',
 '?',
 '’',
 'So',
 'she',
 'was',
 'considering',
 'in',
 'her',
 'own',
 'mind',
 '(',
 'as',
 'well',
 'as',
 'she',
 'could',
 ',',
 'for',
 'the',
 'hot',
 'day',
 'made',
 'her',
 'feel',
 'very',
 'sleepy',
 'and',
 'stupid',
 ')',
 ',',
 'whether',
 'the',
 'pleasure',
 'of',
 'making',
 'a',
 'daisy-chain',
 'would',
 'be',
 'worth',
 'the',
 'trouble',
 'of',
 '

In [0]:
df = data.split()

In [0]:
df

['CHAPTER',
 'I.',
 'Down',
 'the',
 'Rabbit-Hole',
 'Alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'bank,',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'do:',
 'once',
 'or',
 'twice',
 'she',
 'had',
 'peeped',
 'into',
 'the',
 'book',
 'her',
 'sister',
 'was',
 'reading,',
 'but',
 'it',
 'had',
 'no',
 'pictures',
 'or',
 'conversations',
 'in',
 'it,',
 '‘and',
 'what',
 'is',
 'the',
 'use',
 'of',
 'a',
 'book,’',
 'thought',
 'Alice',
 '‘without',
 'pictures',
 'or',
 'conversations?’',
 'So',
 'she',
 'was',
 'considering',
 'in',
 'her',
 'own',
 'mind',
 '(as',
 'well',
 'as',
 'she',
 'could,',
 'for',
 'the',
 'hot',
 'day',
 'made',
 'her',
 'feel',
 'very',
 'sleepy',
 'and',
 'stupid),',
 'whether',
 'the',
 'pleasure',
 'of',
 'making',
 'a',
 'daisy-chain',
 'would',
 'be',
 'worth',
 'the',
 'trouble',
 'of',
 'getting',
 'up',
 'and',
 'picking',
 'the',
 'daisies,',
 'when',
 'sudden

In [0]:
doc = data.replace('--',' ')

In [0]:
docm  = data.split()

In [0]:
docm

['CHAPTER',
 'I.',
 'Down',
 'the',
 'Rabbit-Hole',
 'Alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'bank,',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'do:',
 'once',
 'or',
 'twice',
 'she',
 'had',
 'peeped',
 'into',
 'the',
 'book',
 'her',
 'sister',
 'was',
 'reading,',
 'but',
 'it',
 'had',
 'no',
 'pictures',
 'or',
 'conversations',
 'in',
 'it,',
 '‘and',
 'what',
 'is',
 'the',
 'use',
 'of',
 'a',
 'book,’',
 'thought',
 'Alice',
 '‘without',
 'pictures',
 'or',
 'conversations?’',
 'So',
 'she',
 'was',
 'considering',
 'in',
 'her',
 'own',
 'mind',
 '(as',
 'well',
 'as',
 'she',
 'could,',
 'for',
 'the',
 'hot',
 'day',
 'made',
 'her',
 'feel',
 'very',
 'sleepy',
 'and',
 'stupid),',
 'whether',
 'the',
 'pleasure',
 'of',
 'making',
 'a',
 'daisy-chain',
 'would',
 'be',
 'worth',
 'the',
 'trouble',
 'of',
 'getting',
 'up',
 'and',
 'picking',
 'the',
 'daisies,',
 'when',
 'sudden

In [0]:
tokens = [word for word in docm if word.isalpha()]

In [0]:
tokens

['CHAPTER',
 'Down',
 'the',
 'Alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'once',
 'or',
 'twice',
 'she',
 'had',
 'peeped',
 'into',
 'the',
 'book',
 'her',
 'sister',
 'was',
 'but',
 'it',
 'had',
 'no',
 'pictures',
 'or',
 'conversations',
 'in',
 'what',
 'is',
 'the',
 'use',
 'of',
 'a',
 'thought',
 'Alice',
 'pictures',
 'or',
 'So',
 'she',
 'was',
 'considering',
 'in',
 'her',
 'own',
 'mind',
 'well',
 'as',
 'she',
 'for',
 'the',
 'hot',
 'day',
 'made',
 'her',
 'feel',
 'very',
 'sleepy',
 'and',
 'whether',
 'the',
 'pleasure',
 'of',
 'making',
 'a',
 'would',
 'be',
 'worth',
 'the',
 'trouble',
 'of',
 'getting',
 'up',
 'and',
 'picking',
 'the',
 'when',
 'suddenly',
 'a',
 'White',
 'Rabbit',
 'with',
 'pink',
 'eyes',
 'ran',
 'close',
 'by',
 'There',
 'was',
 'nothing',
 'so',
 'VERY',
 'remarkable',
 'in',
 'nor',
 'did',
 'Alice'

In [0]:
tokens = [word.lower() for word in tokens]

In [0]:
tokens


['chapter',
 'down',
 'the',
 'alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'once',
 'or',
 'twice',
 'she',
 'had',
 'peeped',
 'into',
 'the',
 'book',
 'her',
 'sister',
 'was',
 'but',
 'it',
 'had',
 'no',
 'pictures',
 'or',
 'conversations',
 'in',
 'what',
 'is',
 'the',
 'use',
 'of',
 'a',
 'thought',
 'alice',
 'pictures',
 'or',
 'so',
 'she',
 'was',
 'considering',
 'in',
 'her',
 'own',
 'mind',
 'well',
 'as',
 'she',
 'for',
 'the',
 'hot',
 'day',
 'made',
 'her',
 'feel',
 'very',
 'sleepy',
 'and',
 'whether',
 'the',
 'pleasure',
 'of',
 'making',
 'a',
 'would',
 'be',
 'worth',
 'the',
 'trouble',
 'of',
 'getting',
 'up',
 'and',
 'picking',
 'the',
 'when',
 'suddenly',
 'a',
 'white',
 'rabbit',
 'with',
 'pink',
 'eyes',
 'ran',
 'close',
 'by',
 'there',
 'was',
 'nothing',
 'so',
 'very',
 'remarkable',
 'in',
 'nor',
 'did',
 'alice'

In [0]:
len(set(tokens))

2361

In [0]:
len(tokens)

22622

In [0]:
length = 4
#length = 50 + 1
sequences = list()
for i in range(length, len(tokens)):
	# select sequence of tokens
	seq = tokens[i-length:i]
	# convert into a line
	line = ' '.join(seq)
	# store
	sequences.append(line)

In [0]:
sequences

['chapter down the alice',
 'down the alice was',
 'the alice was beginning',
 'alice was beginning to',
 'was beginning to get',
 'beginning to get very',
 'to get very tired',
 'get very tired of',
 'very tired of sitting',
 'tired of sitting by',
 'of sitting by her',
 'sitting by her sister',
 'by her sister on',
 'her sister on the',
 'sister on the and',
 'on the and of',
 'the and of having',
 'and of having nothing',
 'of having nothing to',
 'having nothing to once',
 'nothing to once or',
 'to once or twice',
 'once or twice she',
 'or twice she had',
 'twice she had peeped',
 'she had peeped into',
 'had peeped into the',
 'peeped into the book',
 'into the book her',
 'the book her sister',
 'book her sister was',
 'her sister was but',
 'sister was but it',
 'was but it had',
 'but it had no',
 'it had no pictures',
 'had no pictures or',
 'no pictures or conversations',
 'pictures or conversations in',
 'or conversations in what',
 'conversations in what is',
 'in what is

In [0]:
filename = 'sequences_of_alice.txt'

In [0]:
datafile = '\n'.join(sequences)
file = open(filename,'w')
file.write(datafile)
file.close()

In [0]:
def load_doc(filename):
	# open the file as read only
	file = open(filename, 'r')
	# read all text
	text = file.read()
	# close the file
	file.close()
	return text
 
# load
in_filename = 'sequences_of_alice.txt'
doc = load_doc(in_filename)
lines = doc.split('\n')

In [0]:
lines

['chapter down the alice',
 'down the alice was',
 'the alice was beginning',
 'alice was beginning to',
 'was beginning to get',
 'beginning to get very',
 'to get very tired',
 'get very tired of',
 'very tired of sitting',
 'tired of sitting by',
 'of sitting by her',
 'sitting by her sister',
 'by her sister on',
 'her sister on the',
 'sister on the and',
 'on the and of',
 'the and of having',
 'and of having nothing',
 'of having nothing to',
 'having nothing to once',
 'nothing to once or',
 'to once or twice',
 'once or twice she',
 'or twice she had',
 'twice she had peeped',
 'she had peeped into',
 'had peeped into the',
 'peeped into the book',
 'into the book her',
 'the book her sister',
 'book her sister was',
 'her sister was but',
 'sister was but it',
 'was but it had',
 'but it had no',
 'it had no pictures',
 'had no pictures or',
 'no pictures or conversations',
 'pictures or conversations in',
 'or conversations in what',
 'conversations in what is',
 'in what is

In [0]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)

In [0]:
sequences = tokenizer.texts_to_sequences(lines)

In [0]:
sequences

[[254, 45, 1, 15],
 [45, 1, 15, 10],
 [1, 15, 10, 235],
 [15, 10, 235, 3],
 [10, 235, 3, 84],
 [235, 3, 84, 26],
 [3, 84, 26, 356],
 [84, 26, 356, 5],
 [26, 356, 5, 273],
 [356, 5, 273, 47],
 [5, 273, 47, 18],
 [273, 47, 18, 469],
 [47, 18, 469, 23],
 [18, 469, 23, 1],
 [469, 23, 1, 2],
 [23, 1, 2, 5],
 [1, 2, 5, 274],
 [2, 5, 274, 151],
 [5, 274, 151, 3],
 [274, 151, 3, 174],
 [151, 3, 174, 25],
 [3, 174, 25, 1257],
 [174, 25, 1257, 6],
 [25, 1257, 6, 19],
 [1257, 6, 19, 658],
 [6, 19, 658, 54],
 [19, 658, 54, 1],
 [658, 54, 1, 659],
 [54, 1, 659, 18],
 [1, 659, 18, 469],
 [659, 18, 469, 10],
 [18, 469, 10, 29],
 [469, 10, 29, 9],
 [10, 29, 9, 19],
 [29, 9, 19, 48],
 [9, 19, 48, 537],
 [19, 48, 537, 25],
 [48, 537, 25, 1258],
 [537, 25, 1258, 8],
 [25, 1258, 8, 36],
 [1258, 8, 36, 34],
 [8, 36, 34, 1],
 [36, 34, 1, 130],
 [34, 1, 130, 5],
 [1, 130, 5, 4],
 [130, 5, 4, 57],
 [5, 4, 57, 15],
 [4, 57, 15, 537],
 [57, 15, 537, 25],
 [15, 537, 25, 28],
 [537, 25, 28, 6],
 [25, 28, 6, 10],


In [0]:
vocab_size = len(tokenizer.word_index) + 1 #not repeating word length

In [0]:
vocab_size

2362

In [0]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'she': 6,
 'said': 7,
 'in': 8,
 'it': 9,
 'was': 10,
 'you': 11,
 'i': 12,
 'as': 13,
 'that': 14,
 'alice': 15,
 'at': 16,
 'with': 17,
 'her': 18,
 'had': 19,
 'all': 20,
 'for': 21,
 'be': 22,
 'on': 23,
 'this': 24,
 'or': 25,
 'very': 26,
 'not': 27,
 'so': 28,
 'but': 29,
 'they': 30,
 'little': 31,
 'he': 32,
 'out': 33,
 'is': 34,
 'his': 35,
 'what': 36,
 'about': 37,
 'if': 38,
 'up': 39,
 'have': 40,
 'were': 41,
 'one': 42,
 'went': 43,
 'project': 44,
 'down': 45,
 'would': 46,
 'by': 47,
 'no': 48,
 'like': 49,
 'when': 50,
 'any': 51,
 'your': 52,
 'do': 53,
 'into': 54,
 'there': 55,
 'could': 56,
 'thought': 57,
 'its': 58,
 'an': 59,
 'then': 60,
 'are': 61,
 'who': 62,
 'my': 63,
 'mock': 64,
 'quite': 65,
 'see': 66,
 'some': 67,
 'must': 68,
 'their': 69,
 'did': 70,
 'how': 71,
 'them': 72,
 'just': 73,
 'time': 74,
 'began': 75,
 'which': 76,
 'from': 77,
 'such': 78,
 'me': 79,
 'only': 80,
 'know': 81,
 'look

In [0]:
sequences = np.array(sequences)

In [0]:
sequences

array([[ 254,   45,    1,   15],
       [  45,    1,   15,   10],
       [   1,   15,   10,  235],
       ...,
       [ 250,  851, 2361,    3],
       [ 851, 2361,    3,  207],
       [2361,    3,  207,   37]])

In [0]:
x,y = sequences[:,:-1],sequences[:,-1]


In [0]:
seq_length = x.shape[1]

In [0]:
from keras.utils import to_categorical

In [0]:
y_train = to_categorical(y,num_classes=vocab_size)

In [0]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
from keras.layers import Embedding

In [0]:
model = Sequential()
model.add(Embedding(vocab_size, 50, input_length=seq_length))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

W0627 17:00:35.403270 140119374497664 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0627 17:00:35.480882 140119374497664 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0627 17:00:35.491413 140119374497664 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 3, 50)             118100    
_________________________________________________________________
lstm_1 (LSTM)                (None, 3, 100)            60400     
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 2362)              238562    
Total params: 507,562
Trainable params: 507,562
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit model
model.fit(x, y_train, batch_size=128, epochs=100)

W0627 17:03:56.376583 140119374497664 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0627 17:03:57.981355 140119374497664 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
22618/22618 [==============================] - 10s 459us/step - loss: 6.2792 - acc: 0.0746
Epoch 2/100
22618/22618 [==============================] - 8s 362us/step - loss: 5.8000 - acc: 0.0783
Epoch 3/100
22618/22618 [==============================] - 8s 355us/step - loss: 5.7746 - acc: 0.0783
Epoch 4/100
22618/22618 [==============================] - 8s 357us/step - loss: 5.7332 - acc: 0.0783
Epoch 5/100
22618/22618 [==============================] - 8s 357us/step - loss: 5.6585 - acc: 0.0784
Epoch 6/100
22618/22618 [==============================] - 8s 359us/step - loss: 5.5848 - acc: 0.0794
Epoch 7/100
22618/22618 [==============================] - 8s 360us/step - loss: 5.4908 - acc: 0.0846
Epoch 8/100
22618/22618 [==============================] - 8s 362us/step - loss: 5.4004 - acc: 0.0898
Epoch 9/100
22618/22618 [==============================] - 8s 361us/step - loss: 5.2927 - acc: 0.0980
Epoch 10/100
22618/22618 [==============================] - 8s 360us/step - loss:

In [0]:
from pickle import dump

In [0]:
model.save('model_alice.h5')
dump(tokenizer,open('tokenizer_alice.pkl','wb'))

In [0]:
del model

In [0]:
from keras.models import load_model

In [0]:
from pickle import load

In [0]:
model = load_model('model_alice.h5')
tokenizer = load(open('tokenizer_alice.pkl','rb'))

['chapter down the alice',
 'down the alice was',
 'the alice was beginning',
 'alice was beginning to',
 'was beginning to get',
 'beginning to get very',
 'to get very tired',
 'get very tired of',
 'very tired of sitting',
 'tired of sitting by',
 'of sitting by her',
 'sitting by her sister',
 'by her sister on',
 'her sister on the',
 'sister on the and',
 'on the and of',
 'the and of having',
 'and of having nothing',
 'of having nothing to',
 'having nothing to once',
 'nothing to once or',
 'to once or twice',
 'once or twice she',
 'or twice she had',
 'twice she had peeped',
 'she had peeped into',
 'had peeped into the',
 'peeped into the book',
 'into the book her',
 'the book her sister',
 'book her sister was',
 'her sister was but',
 'sister was but it',
 'was but it had',
 'but it had no',
 'it had no pictures',
 'had no pictures or',
 'no pictures or conversations',
 'pictures or conversations in',
 'or conversations in what',
 'conversations in what is',
 'in what is

In [0]:
seq_length = len(lines[0].split()) - 1

In [0]:
len(lines)

22618

In [0]:
seed_text = 'what is this one'

In [0]:
seed_text

'what is this one'

In [0]:
encoded = tokenizer.texts_to_sequences([seed_text])[0]

In [0]:

encoded = np.array(encoded)

In [0]:
encoded

array([36, 34, 24, 42])

In [0]:
encod=[]
c=0
for enc in encoded:
  c+=1
  if c!=4:
    encod.append(enc)
  

In [0]:
encod = np.array(encod)
encoded = encod

In [0]:
encoded.shape

(3,)

In [0]:
encoded = encoded.reshape(-1,3)

In [0]:
yhat = model.predict_classes(encoded, verbose=0)

In [0]:
out_word = ''
for word, index in tokenizer.word_index.items():
	if index == yhat:
		out_word = word
		break

In [0]:
out_word

'she'

In [0]:
from keras.preprocessing.sequence import pad_sequences

In [0]:
encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')

In [0]:
encoded

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [36, 34, 24]]], dtype=int32)

In [0]:
seed_text +=out_word 

In [0]:
seed_text

'what is this oneshe'

In [0]:
sequences[:,:-1],sequences[:,-1]

(array([[ 254,   45,    1],
        [  45,    1,   15],
        [   1,   15,   10],
        ...,
        [ 250,  851, 2361],
        [ 851, 2361,    3],
        [2361,    3,  207]]), array([ 15,  10, 235, ...,   3, 207,  37]))